### PR TITLE
add generic-components

### PR DESCRIPTION
**Pull request by thepassle**
Hi all 👋

Just had a chat with Greg, who was interested in these components and felt like they could be valuable building blocks to help with the work that's going on here.

We discussed that a good first step would be to move generic-components to this repo, to start work on the `select` component. We discussed that `open-ui/generic-components` and `thepassle/generic-components` could peacefully co-exist, so while work is going on here, I'll also still be developing them in my own repo as well.

I'm also more than happy to contribute to generic-components at the open-ui side of things. But I also have to note here that I have a fulltime job, and another big open-source project (www.open-wc.org) that I maintain, so my time may be limited. That being said, happy to help wherever I can 🙂

As mentioned above, this is basically just a copy paste from the current generic-components repo to here (I changed the names/links to `@open-ui/generic-components`), to get something started. Feel free to take it from here however you see fit/is helpful.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@thepassle, could you kindly please join the WICG? https://wicg.io ... you might have gotten an email already from the W3C inviting you to join. That will allow us to merge this PR. 

Thanks in advance!

**Comment by thepassle** [comment]
👍 just created an account https://www.w3.org/users/123274

**Comment by marcoscaceres** [comment]
Excellent, thanks @thepassle!

**Comment by gregwhitworth** [comment]
Hey @thepassle thanks for taking the time on this. As I've stepped back and thought about it further I think that the base components should be built alongside the specs and hopefully by the editors themselves. That said, as we move forward if there are areas to integrate some of the OpenWC tools and infra we'll consider leveraging those. Thanks!

**Comment by thepassle** [comment]
All good 🙂

**Pull request closed without merging**
