### PR TITLE
Add writeup on custom select control patterns

### PR DESCRIPTION
**Pull request by wdencker**

### CODE REVIEW

**Comment by gregwhitworth** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by gregwhitworth** [comment]
@levithomason why is Netlify saying that 35 files have changed when it's actually 15? Did it auto kick off a build that resulted in all files being recreated?

**Comment by wdencker** [comment]
@gregwhitworth Updated the filename.

**Comment by gregwhitworth** [comment]
Thanks - following @levithomason response to the Netflify question; as I don't want to screw up the site I'll merge it in.

**Comment by marcoscaceres** [comment]
@wdencker these contributions feel somewhat substantive - particularly the inclusion of use cases.  Would you mind joining the WICG? (join button on the right side-bar): 
https://www.w3.org/community/wicg/

**Comment by gregwhitworth** [comment]
@marcoscaceres I don't know how it's substantive as it's just use cases - it's not a spec of any form. That said, he has joined; but since TPAC is happening we're waiting on Travis & Michael to return to approve his joining. cc: @travisleithead

**Comment by marcoscaceres** [comment]
Great to hear that @wdencker has joined - thank you! 

IANAL, so maybe just being overly cautious... but I feel that things that shape our thinking around incubation, including use cases, have the potential to fall into realm of IPR (e.g., "I suggested that in the use case"). On the other hand, things like fixing typos, usage examples, etc. don't.

**Comment by gregwhitworth** [comment]
Alright - I'm going to go ahead and merge this in.

**Pull request merged**
