### PR TITLE
Adding Spectrum

### PR DESCRIPTION
**Pull request by GarthDB**
I'll fill out all the components and implementation information if this data is a good start.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by GarthDB** [comment]
@marcoscaceres I'm sorry, that's not super clear; what does that mean? Should I have submitted the [css implementation](https://opensource.adobe.com/spectrum-css/) of the design system instead of the main design system website (with usage guidelines)? 

The CSS implementation has an apache-2 license. https://github.com/adobe/spectrum-css

**Comment by GarthDB** [comment]
@marcoscaceres is it a license issue?

**Comment by marcoscaceres** [comment]
No issue:) Just tells our intellectual property rights tracker that you are not making any significant changes. 

To avoid getting flagged, please formally join the WICG (wicg.io). That will automatically clear all future submissions. You should have also received an email about this from our neighborhood friendly IPR bot.

**Comment by GarthDB** [comment]
@marcoscaceres ah, gotcha. Thanks!

**Pull request merged**
