### PR TITLE
update research and analysis for FAST components

### PR DESCRIPTION
**Pull request by chrisdholt**
This PR updates research and analysis to include visuals and updated controls from FAST.

### CODE REVIEW

**Comment by gregwhitworth** [comment]
@chrisdholt I'm kind of confused, I'm pulling down your branch and yet somehow your images aren't showing up locally. @una any chance you can give this a review and you'll be able to see 'em?

**Comment by chrisdholt** [comment]
> @chrisdholt I'm kind of confused, I'm pulling down your branch and yet somehow your images aren't showing up locally. @una any chance you can give this a review and you'll be able to see 'em?

Odd, I'll jump back to this branch and run again to see if I can screenshot.

**Comment by una** [comment]
Sorry for the delay in response. I'm seeing all of the images

**Review by una — APPROVED** [review]

**Comment by chrisdholt** [comment]
> Sorry for the delay in response. I'm seeing all of the images

Thank you @una!

**Pull request merged**
