### PR TITLE
Add Icon research page

### PR DESCRIPTION
**Pull request by tomi-msft**
This PR is to add the research page for the icon component for the following design libraries:

- Ant Design
- Atlaskit
- Fluent UI
- Lightning Design
- Material Design
- Semantic UI
- Stardust

### CODE REVIEW

**Comment by levithomason** [comment]
It looks like the images here are very large and contain a lot of white space. Can we trim them down only the necessary size?

**Review by gregwhitworth — APPROVED** [review]
This looks good to me. Given her history with iconography and design systems I'd like @una to take a look as well.

**Comment by gregwhitworth** [comment]
@tomi-msft can you please join the WICG community group for IPR reasons or we can't land this change.

**Comment by tomi-msft** [comment]
> @tomi-msft can you please join the WICG community group for IPR reasons or we can't land this change.

@gregwhitworth Yes, I've submitted a request, waiting on approval from Travis Leithead!

**Review by una — APPROVED** [review]

**Pull request merged**
