### PR TITLE
feat(concept): allow to collapse concepts sections

### PR DESCRIPTION
**Pull request by assuncaocharles**
- [x] fixes: #118

This PR allows to collapse sections from concepts page

O90E3zQYqa

### CODE REVIEW

**Comment by gregwhitworth** [comment]
@assuncaocharles thank you so much for taking the time to do this. Can you make it so that they are hidden by default or have a collapse/expand all as well?

**Comment by assuncaocharles** [comment]
Hey @gregwhitworth 

added option to expand/collapse all:

NTkIAQ7aRO

**Comment by assuncaocharles** [comment]
Does it work for you @gregwhitworth ?

**Comment by gregwhitworth** [comment]
Sorry for the delay Charles I'm on holiday visiting family. I'll take a look at this later this week. Thanks.

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gregwhitworth** [comment]
@assuncaocharles ok, so now I can expand/collapse them all but I'd expect to be able to collapse them all and then upon click of a single title it would expand that one. Currently the only way to see one I have to expand all of them.

**Comment by assuncaocharles** [comment]
> @assuncaocharles ok, so now I can expand/collapse them all but I'd expect to be able to collapse them all and then upon click of a single title it would expand that one. Currently the only way to see one I have to expand all of them.
> 
> And again - thanks for the help on this.

Hey @gregwhitworth 

Good catch, fixed

**Pull request merged**
