### PR TITLE
Fix contact link

### PR DESCRIPTION
**Pull request by nuragic**
:)

### CODE REVIEW

**Comment by yoavweiss** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by nuragic** [comment]
@yoavweiss sorry what does that mean?

**Comment by yoavweiss** [comment]
That means that your change does not substantively change the specification/feature and as such, doesn't require you to join the WICG in order to merge it (You could still join if you'd like :D).
The message above was an automated one, destined to appease the IPR bots.

**Comment by nuragic** [comment]
Aaah ok... haha gotcha. Well, I'd love to join but I guess I couldn't bring any value at the moment, sorry, thanks anyway! I'll be happy with just fixing the contact link! 😄

**Review by gregwhitworth — APPROVED** [review]

**Pull request merged**
